/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package client;

import java.io.IOException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import org.xml.sax.SAXException;

/**
 * @author Alessandro Zancanella, 751494, sede CO
 *
 * Lorenzo Erba, 748702,Ferialdo Elezi 749721,Alessandro Zancanella
 * 751494,Matteo Cacciarino 748231, sede CO
 *
 * Classe rappresentate l'interfaccia con la quale l'utente puo creare playlist,
 * Creazione della playlist con le canzoni presenti nella repository mostrate
 * nella Jlist sulla sinistra, con la quale dopo aver selezionato un elemento si
 * potra decidere di aggiungerlo alla l'anteprima della playlist da creare per
 * poi una volta terminata l'aggiunta dei brani si puo' confermare il
 * salvataggio della playlist
 *
 */
public class Gui_CreaPlaylist extends javax.swing.JPanel {

    private static String userId, nomePlaylist, anteprimaPlaylist;
    private Canzone canzone;
    private Playlist playlist;

    private static EmotionalSongs previousframe;
    private OperazioniXML opXml;
    private ArrayList<Canzone> listaCanzone;

    /**
     * Creates new form Gui_CreaPlaylist
     */
    public Gui_CreaPlaylist(String userId, String nomePlaylist, EmotionalSongs emo) {
        this.userId = userId;
        this.nomePlaylist = nomePlaylist;
        this.previousframe = emo;
        anteprimaPlaylist = "";

        listaCanzone = new ArrayList<Canzone>();
        playlist = new Playlist(nomePlaylist);
        opXml = new OperazioniXML();
        initComponents();
        DefaultListModel modelloLista = new DefaultListModel<>();
        jLstBrani.setModel(modelloLista);
        //aggiungo alla lista le canzoni lette dal repository
        try {
            listaCanzone = opXml.leggiRepository();
        } catch (SAXException | IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        //aggiungo ogni canzone letta alla lista
        for (Canzone c : listaCanzone) {
            modelloLista.addElement(c.getTitolo());
        }

        this.jLblNomePlaylist.setText(this.jLblNomePlaylist.getText() + this.nomePlaylist);
        this.jLblUserId.setText(this.jLblUserId.getText() + this.userId);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLblNomePlaylist = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLstBrani = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTxtTitolo = new javax.swing.JTextField();
        jTxtAutore = new javax.swing.JTextField();
        jTxtAnno = new javax.swing.JTextField();
        jTxtLink = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLstAnteprima = new javax.swing.JList<>();
        jBtnAggiungiCanzone = new javax.swing.JButton();
        jBtnSalvaSuFile = new javax.swing.JButton();

        jLabel1.setText("<html> <h1 style=\"color:green;\"> <u>Crea Playlist</h1> </html>");

        jLblNomePlaylist.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLblNomePlaylist.setText("Nome della playlist: ");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel3.setText("<html> <b>Scegli i brani da inserire nella playlist:</b>");

        jLstBrani.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jLstBraniValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jLstBrani);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel4.setText("<html> <b>Anteprima canzone selezionata:");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel5.setText("Titolo");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel6.setText("Autore");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel7.setText("Anno");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel8.setText("Link");

        jTxtTitolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtTitoloActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel9.setText("<html> <b>Anteprima playlist:");

        jScrollPane2.setViewportView(jLstAnteprima);

        jBtnAggiungiCanzone.setText("<html> <h3> Aggiungi canzone");
        jBtnAggiungiCanzone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0), 2));
        jBtnAggiungiCanzone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAggiungiCanzoneActionPerformed(evt);
            }
        });

        jBtnSalvaSuFile.setText("<html> <h3> Salva su file");
        jBtnSalvaSuFile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0), 2));
        jBtnSalvaSuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalvaSuFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(336, 336, 336))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblNomePlaylist)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTxtTitolo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtLink, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtAutore, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtAnno, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtnAggiungiCanzone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnSalvaSuFile, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLblNomePlaylist)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnSalvaSuFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnAggiungiCanzone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jTxtTitolo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jTxtAutore, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jTxtAnno, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jTxtLink, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLstBraniValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jLstBraniValueChanged
        // TODO add your handling code here:
        if (!evt.getValueIsAdjusting()) {
            String selected = (String) jLstBrani.getSelectedValue();
            for (Canzone c : listaCanzone) {
                if (c.getTitolo().equals(selected)) {
                    jTxtTitolo.setText(c.getTitolo());
                    jTxtAutore.setText(c.getAutore());
                    jTxtAnno.setText(c.getAnno());
                    jTxtLink.setText(c.getLinkyt());
                }
            }
            jLstBrani.clearSelection();
        }
    }//GEN-LAST:event_jLstBraniValueChanged

    /**
     * Metodo che pulisce tutti i TextField
     *
     */
    private void cleanTextField() {
        jTxtTitolo.setText("");
        jTxtAutore.setText("");
        jTxtAnno.setText("");
        jTxtLink.setText("");
    }

    /**
     * Metodo che pulisce tutti le aree di testo (TextField e TextArea)
     *
     */
    private void cleanAll() {
        cleanTextField();

        DefaultListModel lstmd = (DefaultListModel) this.jLstAnteprima.getModel();
        lstmd.removeAllElements();
    }
    private void jTxtTitoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtTitoloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtTitoloActionPerformed

    /**
     * Metodo che aggiunge i dati inseriti della nuova canzone all'oggetto
     * playlist
     *
     * Invocato al click del bottone Aggiungi Canzone. Verifica che i TextField
     * siano riempiti e crea un oggetto canzone con ci� che � stato inserito,
     * l'oggetto canzone viene aggiunto all'array dell'oggetto playlist,
     * aggiunge la canzone alla textArea e richiama il metodo cleanTextField()
     *
     * @param e evento del click del bottone
     *
     */
    private void jBtnAggiungiCanzoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAggiungiCanzoneActionPerformed
        // TODO add your handling code here:
        if (!jTxtTitolo.getText().isEmpty() && !jTxtAutore.getText().isEmpty() && !jTxtAnno.getText().isEmpty() && !jTxtLink.getText().isEmpty()) {
            DefaultListModel lstmd;
            canzone = new Canzone(jTxtTitolo.getText(), jTxtAutore.getText(), jTxtAnno.getText(), jTxtLink.getText());
            playlist.addBrano(canzone);

            try {
                lstmd = (DefaultListModel) this.jLstAnteprima.getModel();
            } catch (Exception e) {
                lstmd = new DefaultListModel();
            }
            anteprimaPlaylist = canzone.toString();
            lstmd.addElement(anteprimaPlaylist);
            this.jLstAnteprima.setModel(lstmd);
            cleanTextField();
        } else {
            JOptionPane.showMessageDialog(this, "Selezionare una canzone.", "Errore", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtnAggiungiCanzoneActionPerformed
    
    /**
     * Metodo che salva la playlist su file
     *
     * Invocato al click del bottone salva su file. richiama il metodo
     * addPlaylist della classe OperazioniXML, passandogli idUtente,
     * nomePlaylist e i brani della playlist se l'inserimento avviene con
     * successo ritorna sul pannello precedente altrimenti mostra un messaggio
     * di errore nel TextArea
     *
     */
    public void RegistraPlaylist() {
        // TODO add your handling code here:
        boolean result = false;
        anteprimaPlaylist = "";
        if (this.jLstAnteprima.getModel().getSize() == 0) {
            JOptionPane.showMessageDialog(this, "Aggiungere almeno una canzone.", "Errore", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                result = opXml.addPlaylist(userId, nomePlaylist, playlist.getBrani());
                JOptionPane.showMessageDialog(this, "Playlist creata correttamente.", "Info", JOptionPane.INFORMATION_MESSAGE);
                cleanAll();
            } catch (SAXException | IOException e1) {
                // TODO Auto-generated catch block
                e1.printStackTrace();
                JOptionPane.showMessageDialog(this, "Errore #A1024. Errore durante il salvataggio dei brani", "Errore", JOptionPane.ERROR_MESSAGE);
            }
            cleanAll();

        }
    }

    /**
     * Evento click del bottone "Salva su file"
     * @param evt  evento del click bottone
     */
    private void jBtnSalvaSuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalvaSuFileActionPerformed
        this.RegistraPlaylist();

    }//GEN-LAST:event_jBtnSalvaSuFileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAggiungiCanzone;
    private javax.swing.JButton jBtnSalvaSuFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLblNomePlaylist;
    private javax.swing.JList<String> jLstAnteprima;
    private javax.swing.JList<String> jLstBrani;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTxtAnno;
    private javax.swing.JTextField jTxtAutore;
    private javax.swing.JTextField jTxtLink;
    private javax.swing.JTextField jTxtTitolo;
    // End of variables declaration//GEN-END:variables
}
