/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package client;

import common.*;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;

/**
 *
 * @author Lorenzo Erba, 748702
 *
 * Lorenzo Erba, 748702,Ferialdo Elezi 749721,Alessandro Zancanella
 * 751494,Matteo Cacciarino 748231, sede CO
 *
 * Classe rappresentante il panel che mostra i commenti rilasciati dall'utente selezionato
 */
public class notes_Gui extends javax.swing.JPanel {

    //atributo di tipo Emozioni_Canzone contenente le emozioni e le note di tutti gli utenti relativi alla canzone indicata dall'utente
    private Emozioni emo_canzone;
    //attributo di tipo int contenente l'indice della riga selezionata 
    private int selectedrow;
    private InterfacciaServizio is;
    
    /**
     * Costruttore parametrico che inizializza tutti gli attributi
     * 
     * @param emo_canzone variabile di tipo Emozioni_Canzone contenetne la lista delle emozioni e delle note rilasciate da ogni utente relative alla canzone indicata dall'utente
     * @param selectedrow variabile di tipo int contenente l'indice della riga selezionata 
     */
    public notes_Gui(Emozioni emo_canzone, int selectedrow, InterfacciaServizio is) {
        initComponents();
        this.emo_canzone = emo_canzone;
        this.selectedrow = selectedrow;
        this.is=is;
        //invocazione del metodo che popola la textPane
        this.riempiTxtArea();

    }
    
    /**
     * Metodo che permette il popolamento della textPane
     */
    public void riempiTxtArea() {
        //ottengo l'id dell'utente relativo alle emozioni selezionate nel Panel precedente
        String idUtente = this.emo_canzone.getEmozionicanzoni().get(selectedrow).getCodiceFiscale();
        //se l'idUtente è uguale a "-1" stampo l'errore
        if (idUtente.equals("-1")) {
            JOptionPane.showMessageDialog(null, "Errore #A1017. Errore durante il settings dell'idUtente.", "Errore", JOptionPane.ERROR_MESSAGE);
        } else {
            //settings della jLabel con l'idutente ottenuto
            this.jLabel1.setText("<html> <h1 style='color:green;'><u>Note dell'utente</u>: " + idUtente + "</h1>");
            //ottengo tutte le note rilasciate dall'utente idutente relative a ogni emozione
            String notes = this.emo_canzone.getEmozionicanzoni().get(selectedrow).getCodiceFiscale();
            //rendo la textPane non modificale
            this.jTextPane1.setEditable(false);
            //settings del tipo di contenuto della textPane in formato html
            this.jTextPane1.setContentType("text/html");
            //inserimento delle note nella textPane
            this.jTextPane1.setText(notes);
            //setting della scrollbar all'inzio della textPane
            this.jTextPane1.setCaretPosition(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        jLabel1.setText("<html> <h1 style=\"color:green;\"><u>Note dell'utente:</u></h1>");

        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(344, 344, 344))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
