/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package client;

import common.*;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;

/**
 *
 * @author Lorenzo Erba, 748702
 *
 * Lorenzo Erba, 748702,Ferialdo Elezi 749721,Alessandro Zancanella
 * 751494,Matteo Cacciarino 748231, sede CO
 *
 * Classe rappresentante il panel che mostra i commenti rilasciati dall'utente selezionato
 */
public class notes_Gui extends javax.swing.JPanel {

    //atributo di tipo Emozioni_Canzone contenente le emozioni e le note di tutti gli utenti relativi alla canzone indicata dall'utente
    private Emozioni emo_canzone;
    //attributo di tipo int contenente l'indice della riga selezionata 
    private int selectedrow;
    private InterfacciaServizio is;
    
    /**
     * Costruttore parametrico che inizializza tutti gli attributi
     * 
     * @param emo_canzone variabile di tipo Emozioni_Canzone contenetne la lista delle emozioni e delle note rilasciate da ogni utente relative alla canzone indicata dall'utente
     * @param selectedrow variabile di tipo int contenente l'indice della riga selezionata 
     */
    public notes_Gui(Emozioni emo_canzone, int selectedrow, InterfacciaServizio is) {
        initComponents();
        this.emo_canzone = emo_canzone;
        this.selectedrow = selectedrow;
        this.is=is;
        //invocazione del metodo che popola la textPane
        this.riempiTxtArea();

    }
    
    /**
     * Metodo che permette il popolamento della textPane
     */
    public void riempiTxtArea() {
        //ottengo l'id dell'utente relativo alle emozioni selezionate nel Panel precedente
        String idUtente = this.emo_canzone.getEmozionicanzoni().get(selectedrow).getCodiceFiscale();
        //se l'idUtente è uguale a "-1" stampo l'errore
        if (idUtente.equals("-1")) {
            JOptionPane.showMessageDialog(null, "Errore #A1017. Errore durante il settings dell'idUtente.", "Errore", JOptionPane.ERROR_MESSAGE);
        } else {
            //settings della jLabel con l'idutente ottenuto
            this.jLabel1.setText("<html> <h1 style='color:green;'><u>Note dell'utente</u>: " + idUtente + "</h1>");
            //ottengo tutte le note rilasciate dall'utente idutente relative a ogni emozione
            String notes = "Amazement : " + this.emo_canzone.getEmozionicanzoni().get(selectedrow).getAmazement_notes() + "\r\n"+"\r\n"+
                            "Nostalgia : " + this.emo_canzone.getEmozionicanzoni().get(selectedrow).getNostalgia_notes() + "\r\n"+"\r\n"+
                            "Calmness : " + this.emo_canzone.getEmozionicanzoni().get(selectedrow).getCalmness_notes() + "\r\n"+"\r\n"+
                            "Power : " + this.emo_canzone.getEmozionicanzoni().get(selectedrow).getPower_notes() + "\r\n"+"\r\n"+
                            "Joy : " + this.emo_canzone.getEmozionicanzoni().get(selectedrow).getJoy_notes() + "\r\n"+"\r\n"+
                            "Tension : " + this.emo_canzone.getEmozionicanzoni().get(selectedrow).getTension_notes() + "\r\n"+"\r\n"+
                            "Sadness : " + this.emo_canzone.getEmozionicanzoni().get(selectedrow).getSadness_notes() + "\r\n"+"\r\n"+
                            "Tenderness : " + this.emo_canzone.getEmozionicanzoni().get(selectedrow).getTenderness_notes() + "\r\n"+"\r\n"+
                            "Solemnity : " + this.emo_canzone.getEmozionicanzoni().get(selectedrow).getSolemnity_notes() + "\r\n";
           
            //inserimento delle note nella textPane
            this.jTextArea1.setText(notes);
            //rendo la textPane non modificale
            this.jTextArea1.setEditable(false);
            //setting della scrollbar all'inzio della textPane
            this.jTextArea1.setCaretPosition(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jLabel1.setText("<html> <h1 style=\"color:green;\"><u>Note dell'utente:</u></h1>");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(372, 372, 372))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
